// Historical strength-training backlog, transcribed from the user's
// spreadsheet (2/13/26 -> 9/3/26). Dates are kept EXACTLY as written in the
// source sheet, including the two 2025 entries and the two separate 8/11/2026
// sessions. Freeform commentary from the sheet is preserved in `notes`.
//
// One-time import surface: /log/import reads this and writes it through the
// normal logStrength() path so PRs, XP, and the feed all behave identically to
// hand-logged workouts.

export type BacklogSet = {
  exercise: string;
  weightLb: string;
  reps: string;
};

export type BacklogWorkout = {
  /** Local date, YYYY-MM-DD, exactly as dated in the source sheet. */
  date: string;
  title: string;
  notes: string;
  sets: BacklogSet[];
};

/** Repeat one set spec `n` times. */
function xN(n: number, exercise: string, weightLb: string, reps: string): BacklogSet[] {
  return Array.from({ length: n }, () => ({ exercise, weightLb, reps }));
}

/** A single set. */
function s(exercise: string, weightLb: string, reps: string): BacklogSet {
  return { exercise, weightLb, reps };
}

export const BACKLOG: BacklogWorkout[] = [
  {
    date: "2026-02-13",
    title: "Shoulders and arms",
    notes:
      "Sets taken to failure; reps not recorded. Overhead tricep rope extensions felt ineffective.",
    sets: [
      ...xN(2, "Dumbbell Bicep Curl", "25", ""),
      ...xN(2, "Dumbbell Bicep Curl", "22.5", ""),
      ...xN(3, "Brachialis Curl", "20", ""),
      s("Hammer Curl", "15", ""),
      ...xN(2, "Forearm Curl", "20", ""),
      ...xN(2, "Supinated Wrist Curl", "20", ""),
      s("Overhead Tricep Rope Extension", "20", ""),
      ...xN(3, "Tricep Pushdown", "20", ""),
      s("Shoulder Press", "78", ""),
      s("Shoulder Press", "58", ""),
      ...xN(3, "Shoulder Press", "58", ""),
    ],
  },
  {
    date: "2026-04-01",
    title: "Arms and shoulders",
    notes:
      "Triceps: second set was bad so dropped 30 -> 20 lbs, third was even worse, fourth much better after a 5 minute break, got cooked on the fifth. Shoulder press: after the first 118 lb set could only do a couple of reps per set.",
    sets: [
      ...xN(2, "Dumbbell Bicep Curl", "", "7"),
      ...xN(2, "Dumbbell Bicep Curl", "", "5"),
      ...xN(2, "Pronated Wrist Curl", "12.5", ""),
      ...xN(2, "Supinated Wrist Curl", "22.5", ""),
      ...xN(2, "Tricep Extension", "30", ""),
      ...xN(3, "Tricep Extension", "20", ""),
      s("Shoulder Press", "98", ""),
      s("Shoulder Press", "118", ""),
      ...xN(2, "Seated Dip", "75", ""),
      s("Seated Dip", "85", ""),
      s("Seated Dip", "90", ""),
    ],
  },
  {
    date: "2026-04-03",
    title: "Legs",
    notes:
      "Leg push: mixed basic, half-low and wide stances and felt confused about what to do. Untrained legs — maybe just stick to the basic stance.",
    sets: [
      ...xN(2, "Leg Press Down", "70", "12"),
      s("Leg Press Down", "75", "11"),
      s("Leg Press Down", "80", "7"),
      s("Leg Press Down", "75", "8"),
      s("Leg Press", "135", "12"),
      s("Leg Press", "145", "7"),
      s("Leg Press", "130", "8"),
      s("Leg Press", "145", "8"),
      ...xN(4, "Inner Thigh (Adductor)", "95", "10"),
      ...xN(2, "Outer Thigh (Abductor)", "60", "10"),
      s("Outer Thigh (Abductor)", "70", "10"),
    ],
  },
  {
    date: "2026-04-06",
    title: "Arms",
    notes: "",
    sets: [
      s("Dumbbell Bicep Curl", "27.5", "7"),
      s("Dumbbell Bicep Curl", "27.5", "8"),
      s("Dumbbell Bicep Curl", "25", "6"),
      s("Dumbbell Bicep Curl", "25", "10"),
      ...xN(5, "Pronated Wrist Curl", "10", "10"),
      s("Supinated Wrist Curl", "22.5", "12"),
      s("Supinated Wrist Curl", "25", "10"),
      s("Supinated Wrist Curl", "22.5", "10"),
      s("Supinated Wrist Curl", "15", "8"),
      s("Tricep Pushdown", "20", "17"),
      ...xN(2, "Tricep Pushdown", "20", "16"),
      s("Tricep Pushdown", "20", "10"),
    ],
  },
  {
    date: "2026-04-08",
    title: "Legs",
    notes:
      "Seated leg curls started to feel a bit hard by the third set. Inner thigh second set: 10 clean reps but had to take a couple of breaks after 6.",
    sets: [
      s("Outer Thigh (Abductor)", "70", "12"),
      s("Outer Thigh (Abductor)", "80", "12"),
      s("Leg Press", "130", "12"),
      s("Leg Press", "145", "14"),
      s("Leg Press", "145", "12"),
      s("Seated Leg Curl", "70", "12"),
      s("Seated Leg Curl", "75", "12"),
      s("Seated Leg Curl", "75", "10"),
      s("Seated Leg Curl", "70", "11"),
      s("Inner Thigh (Adductor)", "90", "12"),
      s("Inner Thigh (Adductor)", "100", "11"),
      s("Inner Thigh (Adductor)", "95", "12"),
    ],
  },
  {
    date: "2026-04-13",
    title: "Arms",
    notes:
      "Last tricep pushdown set: 7 reps, took a couple of seconds break then did a couple more.",
    sets: [
      s("Dumbbell Bicep Curl", "25", "10"),
      s("Dumbbell Bicep Curl", "25", "9"),
      s("Dumbbell Bicep Curl", "25", "8"),
      s("Hammer Curl", "17.5", "18"),
      s("Hammer Curl", "22.5", "10"),
      s("Hammer Curl", "22.5", "8"),
      s("Supinated Wrist Curl", "22.5", "12"),
      s("Supinated Wrist Curl", "25", "10"),
      s("Tricep Pushdown", "20", "15"),
      s("Tricep Pushdown", "20", "8"),
      s("Tricep Pushdown", "20", "12"),
      s("Tricep Pushdown", "20", "11"),
      s("Tricep Pushdown", "20", "7"),
    ],
  },
  {
    date: "2026-04-14",
    title: "Legs",
    notes:
      "Inner thigh: 11th rep was hard, aimed for 12; third set really struggled on the 8th. Outer thigh 90 lbs: tried pausing for a second but quickly felt overwhelmed by the 5th rep. Calves 50 lbs: felt the load towards the end but did not struggle insanely much.",
    sets: [
      s("Leg Press", "130", "12"),
      s("Leg Press", "145", "12"),
      s("Leg Press", "145", "10"),
      s("Leg Press", "150", "8"),
      s("Seated Leg Curl", "70", "13"),
      s("Seated Leg Curl", "75", "11"),
      s("Seated Leg Curl", "75", "10"),
      s("Leg Extension", "90", "16"),
      s("Leg Extension", "100", "12"),
      s("Leg Extension", "110", "11"),
      s("Inner Thigh (Adductor)", "90", "12"),
      s("Inner Thigh (Adductor)", "100", "11"),
      s("Inner Thigh (Adductor)", "100", "9"),
      s("Outer Thigh (Abductor)", "70", "15"),
      s("Outer Thigh (Abductor)", "80", "14"),
      s("Outer Thigh (Abductor)", "90", "7"),
      s("Standing Calf Raise", "40", "15"),
      s("Standing Calf Raise", "50", "12"),
      s("Standing Calf Raise", "40", "11"),
    ],
  },
  {
    date: "2026-04-17",
    title: "Arms",
    notes:
      "Overhead dumbbell tricep: tried 15 lbs but too hard, could only do about 2 reps. Supinated wrist curls: 9 reps on the right on the second set.",
    sets: [
      s("Dumbbell Bicep Curl", "25", "12"),
      s("Dumbbell Bicep Curl", "25", "9"),
      s("Dumbbell Bicep Curl", "25", "8"),
      s("Dumbbell Bicep Curl", "25", "9"),
      s("Tricep Pushdown", "20", "25"),
      s("Tricep Pushdown", "20", "8"),
      s("Tricep Pushdown", "30", "4"),
      s("Tricep Pushdown", "20", "13"),
      s("Hammer Curl (Cross Body)", "22.5", "12"),
      s("Hammer Curl", "22.5", "12"),
      s("Overhead Dumbbell Tricep Extension", "12", "10"),
      s("Overhead Dumbbell Tricep Extension", "15", "2"),
      s("Supinated Wrist Curl", "25", "12"),
      s("Supinated Wrist Curl", "25", "10"),
      ...xN(2, "Pronated Wrist Curl", "12", "12"),
    ],
  },
  {
    date: "2026-04-20",
    title: "Legs",
    notes:
      "Could not do 10 reps on the fourth 150 lb set so switched to 130. Inner thigh: 6 reps at 100 before needing to pause, switched to 90 for 2, then about 2 reps at 100 and could not do a third. Calves: 45 lbs got hard starting at rep 12.",
    sets: [
      s("Leg Press", "130", "12"),
      s("Leg Press", "145", "12"),
      s("Leg Press", "150", "10"),
      s("Leg Press", "150", "5"),
      s("Leg Press", "130", "5"),
      s("Seated Leg Curl", "70", "15"),
      s("Seated Leg Curl", "75", "12"),
      s("Seated Leg Curl", "75", "12"),
      s("Inner Thigh (Adductor)", "90", "15"),
      s("Inner Thigh (Adductor)", "100", "12"),
      s("Inner Thigh (Adductor)", "100", "6"),
      s("Inner Thigh (Adductor)", "90", "2"),
      s("Inner Thigh (Adductor)", "100", "2"),
      s("Leg Extension", "90", "15"),
      s("Leg Extension", "100", "12"),
      s("Leg Extension", "110", "12"),
      s("Standing Calf Raise", "40", "15"),
      s("Standing Calf Raise", "45", "15"),
      s("Standing Calf Raise", "45", "12"),
    ],
  },
  {
    date: "2026-04-22",
    title: "Push — chest, shoulders, triceps",
    notes: "",
    sets: [
      s("Chest Press Machine", "75", "12"),
      s("Chest Press Machine", "95", "8"),
      s("Chest Press Machine", "75", "4"),
      s("Chest Press Machine", "75", "7"),
      s("Chest Press Machine", "55", "4"),
      s("Seated Dip (Wide Grip)", "75", "12"),
      s("Seated Dip (Wide Grip)", "85", "10"),
      s("Seated Dip (Wide Grip)", "85", "6"),
      s("Seated Dip (Wide Grip)", "85", "8"),
      s("Shoulder Press", "98", "6"),
      s("Shoulder Press", "58", "7"),
      s("Shoulder Press", "98", "5"),
      s("Shoulder Press", "78", "4"),
      s("Shoulder Press", "58", "2"),
      s("Tricep Pushdown", "20", "10"),
      ...xN(3, "Tricep Pushdown", "20", "12"),
    ],
  },
  {
    date: "2026-04-27",
    title: "Legs",
    notes:
      "Leg press: first two easy, 150 felt good, fourth set started stalling after 8 but all done with good control. Prone leg curls: might not be getting full contractions, only holding about 1.5 seconds. Leg extension: better control with 90 and 100 than 110. Inner thigh had amazing control.",
    sets: [
      s("Leg Press", "130", "12"),
      s("Leg Press", "137.5", "12"),
      s("Leg Press", "150", "10"),
      s("Leg Press", "150", "10"),
      s("Leg Press", "130", "12"),
      s("Prone Leg Curl", "60", "12"),
      s("Prone Leg Curl", "60", "10"),
      s("Prone Leg Curl", "65", "9"),
      s("Leg Extension", "90", "15"),
      s("Leg Extension", "100", "12"),
      s("Leg Extension", "110", "12"),
      s("Outer Thigh (Abductor)", "70", "15"),
      s("Outer Thigh (Abductor)", "80", "12"),
      s("Outer Thigh (Abductor)", "80", "8"),
      s("Outer Thigh (Abductor)", "70", "7"),
      s("Inner Thigh (Adductor)", "90", "15"),
      s("Inner Thigh (Adductor)", "100", "12"),
      s("Inner Thigh (Adductor)", "90", "13"),
      ...xN(2, "Standing Calf Raise", "45", "12"),
      s("Standing Calf Raise", "45", "9"),
      s("Standing Calf Raise", "40", "3"),
    ],
  },
  {
    date: "2026-04-28",
    title: "Pull — back and biceps",
    notes:
      "60 lb low rows started to get hard but good control. Love the burn on lat pulldowns. Seated mid row felt mostly in the forearms. Biceps faded fast — could not even do 8 on the second set.",
    sets: [
      s("Low Row", "50", "12"),
      s("Low Row", "60", "12"),
      s("Low Row", "50", "12"),
      s("Lat Pulldown", "60", "12"),
      s("Lat Pulldown", "60", "12"),
      s("Lat Pulldown", "70", "12"),
      ...xN(2, "Seated Mid Row", "85", "12"),
      ...xN(2, "Rear Delt Fly", "47.5", "12"),
      s("Rear Delt Fly", "40", "12"),
      s("Rear Delt Fly", "40", "8"),
      s("Rear Delt Fly", "30", "4"),
      s("Dumbbell Bicep Curl", "25", "11"),
      s("Dumbbell Bicep Curl", "25", "7"),
      s("Dumbbell Bicep Curl", "25", "3"),
      s("Dumbbell Bicep Curl", "20", "3"),
      s("Hammer Curl", "20", "5"),
    ],
  },
  {
    date: "2026-04-30",
    title: "Legs",
    notes:
      "Inner thigh: last set got too hard, had to pause about 10 seconds before getting to 13 reps. Calves: it seems like 12 is my max.",
    sets: [
      s("Leg Press", "137.5", "12"),
      s("Leg Press", "150", "12"),
      s("Leg Press", "150", "8"),
      ...xN(2, "Prone Leg Curl", "60", "12"),
      s("Prone Leg Curl", "65", "10"),
      ...xN(2, "Outer Thigh (Abductor)", "70", "15"),
      s("Outer Thigh (Abductor)", "80", "12"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "12"),
      s("Inner Thigh (Adductor)", "90", "13"),
      ...xN(2, "Standing Calf Raise", "45", "12"),
      s("Standing Calf Raise", "45", "11"),
    ],
  },
  {
    date: "2026-05-05",
    title: "Legs",
    notes:
      "Leg press 137.5: 5/10 difficulty, a bit short of breath for about a minute, feeling ok to great. 150 was very clean and settled better after about 30 seconds. Last two sets used a wider horizontal stance. Outer thigh: felt the burn towards the 11th rep. Calves skipped because I did not want to wait.",
    sets: [
      s("Seated Leg Curl", "60", "13"),
      s("Seated Leg Curl", "70", "12"),
      s("Seated Leg Curl", "75", "9"),
      s("Seated Leg Curl", "75", "11"),
      s("Leg Press", "137.5", "12"),
      s("Leg Press", "150", "12"),
      ...xN(2, "Leg Press", "150", "10"),
      ...xN(2, "Outer Thigh (Abductor)", "70", "15"),
      s("Outer Thigh (Abductor)", "80", "10"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "12"),
      s("Inner Thigh (Adductor)", "90", "12"),
    ],
  },
  {
    date: "2026-05-07",
    title: "Push — chest, shoulders, triceps",
    notes:
      "Chest press: first set at 0 degrees, the rest at 45 degrees. Tricep pushdown second set: had to stop at 7 reps.",
    sets: [
      s("Seated Chest Press", "75", "12"),
      s("Seated Chest Press", "75", "7"),
      s("Seated Chest Press", "75", "4"),
      s("Seated Chest Press", "55", "3"),
      s("Seated Chest Press", "55", "8"),
      s("Seated Chest Press", "55", "4"),
      s("Shoulder Press", "58", "12"),
      s("Shoulder Press", "58", "8"),
      s("Seated Dip", "75", "12"),
      s("Seated Dip", "85", "5"),
      s("Seated Dip", "75", "4"),
      s("Seated Dip", "85", "4"),
      s("Seated Dip", "75", "2"),
      s("Tricep Pushdown", "20", "12"),
      s("Tricep Pushdown", "20", "10"),
      s("Tricep Pushdown", "20", "10"),
    ],
  },
  {
    date: "2026-05-11",
    title: "Legs",
    notes:
      "Outer thigh 80 lbs: last two tough, took a 12 second break then did 3 more.",
    sets: [
      s("Leg Press", "130", "12"),
      s("Leg Press", "135", "12"),
      ...xN(3, "Leg Press", "150", "12"),
      s("Outer Thigh (Abductor)", "70", "15"),
      s("Outer Thigh (Abductor)", "80", "15"),
      s("Seated Leg Curl", "70", "12"),
      s("Seated Leg Curl", "75", "11"),
      s("Seated Leg Curl", "75", "12"),
      ...xN(3, "Inner Thigh (Adductor)", "100", "12"),
      s("Standing Calf Raise", "45", "12"),
      s("Standing Calf Raise", "50", "8"),
    ],
  },
  {
    date: "2025-05-14",
    title: "Legs",
    notes:
      "Leg press: smooth control, kinda slammed the weights on rep 9 of the first 155 set, second 155 set smooth with no slamming, third slammed once around rep 10-11 — more out of breath but decent recovery. Seated leg curl last set: could not go past 8, paused 10 seconds and did 2 more. Inner thigh 110: had to switch down to 100 and even then 4 more was hard.",
    sets: [
      s("Leg Press", "140", "12"),
      s("Leg Press", "155", "10"),
      s("Leg Press", "155", "11"),
      s("Leg Press", "155", "12"),
      s("Seated Leg Curl", "75", "12"),
      ...xN(3, "Seated Leg Curl", "80", "10"),
      s("Outer Thigh (Abductor)", "70", "15"),
      ...xN(2, "Outer Thigh (Abductor)", "80", "13"),
      s("Inner Thigh (Adductor)", "100", "15"),
      s("Inner Thigh (Adductor)", "110", "8"),
      s("Inner Thigh (Adductor)", "100", "4"),
      s("Inner Thigh (Adductor)", "100", "12"),
      s("Standing Calf Raise", "45", "15"),
      ...xN(3, "Standing Calf Raise", "50", "12"),
    ],
  },
  {
    date: "2026-05-18",
    title: "Legs",
    notes: "Leg press 160 had great control.",
    sets: [
      s("Leg Press", "145", "12"),
      s("Leg Press", "160", "10"),
      s("Leg Press", "160", "11"),
      s("Leg Press", "160", "12"),
      s("Seated Leg Curl", "75", "12"),
      ...xN(3, "Seated Leg Curl", "80", "10"),
      s("Outer Thigh (Abductor)", "70", "15"),
      s("Outer Thigh (Abductor)", "80", "12"),
      s("Outer Thigh (Abductor)", "80", "12"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "15"),
      s("Inner Thigh (Adductor)", "110", "10"),
      s("Standing Calf Raise", "50", "15"),
      ...xN(3, "Standing Calf Raise", "55", "12"),
    ],
  },
  {
    date: "2026-05-25",
    title: "Legs",
    notes:
      "Used the other smaller leg press machine. Inner thigh: 110 was too hard, could only do 7 partial reps, so switched to 90 for about 6, took a minute break, then 100 for 10.",
    sets: [
      s("Leg Press (Smaller Machine)", "150", "15"),
      ...xN(3, "Leg Press (Smaller Machine)", "180", "15"),
      s("Seated Leg Curl", "70", "13"),
      s("Seated Leg Curl", "70", "5"),
      s("Seated Leg Curl", "75", "6"),
      s("Prone Leg Curl", "50", "8"),
      s("Prone Leg Curl", "55", "6"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "15"),
      s("Inner Thigh (Adductor)", "110", "7"),
      s("Inner Thigh (Adductor)", "90", "6"),
      s("Inner Thigh (Adductor)", "100", "10"),
      s("Outer Thigh (Abductor)", "70", "15"),
      ...xN(3, "Outer Thigh (Abductor)", "80", "12"),
      s("Standing Calf Raise", "50", "15"),
      s("Standing Calf Raise", "50", "12"),
      ...xN(2, "Standing Calf Raise", "45", "11"),
    ],
  },
  {
    date: "2026-05-26",
    title: "Pull — back and biceps",
    notes: "",
    sets: [
      ...xN(2, "Low Row", "50", "10"),
      s("Low Row", "60", "10"),
      s("Low Row", "55", "10"),
      ...xN(2, "Lat Pulldown (Wide Grip)", "60", "12"),
      s("Lat Pulldown (Wide Grip)", "70", "10"),
      s("Lat Pulldown (Wide Grip)", "60", "5"),
      s("Lat Pulldown (Wide Grip)", "70", "10"),
      ...xN(2, "Rear Delt Fly", "40", "12"),
      s("Rear Delt Fly", "45", "10"),
      s("Rear Delt Fly", "30", "16"),
      s("Dumbbell Bicep Curl", "22.5", "12"),
      s("Dumbbell Bicep Curl", "17.5", "3"),
      s("Dumbbell Bicep Curl", "22.5", "3"),
      s("Dumbbell Bicep Curl", "17.5", "4"),
    ],
  },
  {
    date: "2026-06-01",
    title: "Legs",
    notes:
      "Used the harder leg press machine. Inner thigh: wider stretches than ever before; last set 6 reps, took a 10 second break and did 5 more.",
    sets: [
      s("Leg Press", "145", "12"),
      s("Leg Press", "160", "12"),
      s("Leg Press", "160", "11"),
      s("Leg Press", "145", "11"),
      s("Prone Leg Curl", "50", "12"),
      s("Prone Leg Curl", "55", "12"),
      ...xN(2, "Prone Leg Curl", "60", "10"),
      s("Inner Thigh (Adductor)", "100", "12"),
      s("Inner Thigh (Adductor)", "100", "7"),
      s("Inner Thigh (Adductor)", "90", "4"),
      s("Inner Thigh (Adductor)", "90", "11"),
      s("Outer Thigh (Abductor)", "70", "12"),
      ...xN(2, "Outer Thigh (Abductor)", "80", "12"),
      s("Outer Thigh (Abductor)", "80", "6"),
      s("Outer Thigh (Abductor)", "70", "5"),
      s("Standing Calf Raise", "50", "13"),
      ...xN(2, "Standing Calf Raise", "55", "12"),
      s("Standing Calf Raise", "60", "10"),
    ],
  },
  {
    date: "2026-06-04",
    title: "Legs — hack squat day",
    notes:
      "Hack squats with one 35 lb plate on each end. Standing calves: the second 60 lb set felt tough around rep 10 and the calves felt like burning.",
    sets: [
      ...xN(4, "Hack Squat", "70", "10"),
      s("Prone Leg Curl", "55", "12"),
      ...xN(2, "Prone Leg Curl", "60", "12"),
      s("Prone Leg Curl", "60", "10"),
      s("Outer Thigh (Abductor)", "70", "12"),
      ...xN(3, "Outer Thigh (Abductor)", "80", "12"),
      ...xN(3, "Inner Thigh (Adductor)", "100", "12"),
      s("Standing Calf Raise", "55", "15"),
      ...xN(2, "Standing Calf Raise", "60", "12"),
      s("Standing Calf Raise", "65", "10"),
    ],
  },
  {
    date: "2026-06-08",
    title: "Legs — hack squat day",
    notes:
      "Prone leg curls: last 4 reps of the third set did not feel like full contractions, and the last 6 of the fourth set were not good at all — next time stick to 55-60 lbs and focus on more volume. Inner thigh: should stick to 100 lbs but more volume. Calves: 65 lbs at rep 10 is where the burn really hit, pushed 2 more but the last showed signs of struggle.",
    sets: [
      s("Hack Squat", "70", "12"),
      s("Hack Squat", "70", "12"),
      s("Hack Squat", "70", "10"),
      s("Hack Squat", "70", "11"),
      ...xN(3, "Prone Leg Curl", "60", "12"),
      s("Prone Leg Curl", "55", "12"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "12"),
      s("Inner Thigh (Adductor)", "110", "5"),
      s("Inner Thigh (Adductor)", "100", "4"),
      s("Outer Thigh (Abductor)", "80", "12"),
      s("Outer Thigh (Abductor)", "80", "15"),
      s("Outer Thigh (Abductor)", "80", "13"),
      s("Outer Thigh (Abductor)", "80", "12"),
      s("Standing Calf Raise", "60", "15"),
      ...xN(2, "Standing Calf Raise", "60", "12"),
      s("Standing Calf Raise", "65", "12"),
    ],
  },
  {
    date: "2026-06-11",
    title: "Legs — hack squat day",
    notes:
      "Hack squats: third set took a 10 second break after rep 9; fourth needed two 10 second breaks at reps 7 and 10. Prone leg curls: hamstrings burn a lot, did not want to push too hard. Inner thigh: losing strength after the second set so switched to 90 to failure. Outer thigh last set: took a 12 second break and did 4 more good reps.",
    sets: [
      s("Hack Squat", "70", "11"),
      s("Hack Squat", "70", "11"),
      s("Hack Squat", "70", "12"),
      s("Hack Squat", "70", "12"),
      ...xN(2, "Prone Leg Curl", "55", "12"),
      s("Prone Leg Curl", "50", "9"),
      s("Inner Thigh (Adductor)", "100", "12"),
      s("Inner Thigh (Adductor)", "100", "14"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "8"),
      s("Inner Thigh (Adductor)", "90", "12"),
      s("Outer Thigh (Abductor)", "80", "12"),
      s("Outer Thigh (Abductor)", "80", "13"),
      s("Outer Thigh (Abductor)", "80", "14"),
      s("Outer Thigh (Abductor)", "80", "15"),
      s("Standing Calf Raise", "60", "13"),
      s("Standing Calf Raise", "65", "13"),
      s("Standing Calf Raise", "65", "14"),
    ],
  },
  {
    date: "2026-07-06",
    title: "Arms",
    notes:
      "Bicep curls: 25 lbs was too heavy to finish the set (dropped to 20 for 3 more); last set left arm reached failure first. Tricep pushdowns went easy, easy-to-moderate, then moderate-to-hard. Hammer curl form became sloppy and the left arm was weaker.",
    sets: [
      s("Dumbbell Bicep Curl", "20", "7"),
      s("Dumbbell Bicep Curl", "25", "7"),
      s("Dumbbell Bicep Curl", "20", "3"),
      s("Dumbbell Bicep Curl", "20", "10"),
      s("Dumbbell Bicep Curl", "20", "6"),
      s("Tricep Pushdown", "20", "17"),
      s("Tricep Pushdown", "20", "16"),
      s("Tricep Pushdown", "20", "15"),
      s("Tricep Pushdown", "20", "10"),
      ...xN(3, "Hammer Curl", "15", "10"),
    ],
  },
  {
    date: "2026-07-08",
    title: "Legs — hack squat day",
    notes:
      "Hack squats 35 lbs per side; 2 minute rest after set 3 and set 4 required two 8 second rest-pause breaks. Prone leg curls: last 2 reps of set 2 were difficult, set 3 lost quality after 5 good reps. Outer thigh was hard and felt lethargic afterwards, so ended the workout.",
    sets: [
      ...xN(4, "Hack Squat", "70", "10"),
      s("Prone Leg Curl", "55", "11"),
      s("Prone Leg Curl", "55", "11"),
      s("Prone Leg Curl", "55", "5"),
      ...xN(2, "Outer Thigh (Abductor)", "80", "12"),
    ],
  },
  {
    date: "2026-07-20",
    title: "Legs",
    notes:
      "Used the harder leg press machine. Prone leg curls: third set switched down to 50 lbs for the last 4 reps. Calves: after the 60 lb sets did 4 sets at 50 lbs.",
    sets: [
      s("Leg Press", "145", "10"),
      s("Leg Press", "150", "11"),
      s("Leg Press", "160", "11"),
      ...xN(2, "Prone Leg Curl", "55", "12"),
      s("Prone Leg Curl", "55", "8"),
      s("Prone Leg Curl", "50", "4"),
      s("Prone Leg Curl", "50", "10"),
      ...xN(3, "Inner Thigh (Adductor)", "100", "10"),
      s("Inner Thigh (Adductor)", "100", "8"),
      s("Standing Calf Raise", "60", "15"),
      s("Standing Calf Raise", "60", "13"),
      s("Standing Calf Raise", "60", "12"),
      s("Standing Calf Raise", "60", "11"),
      ...xN(4, "Standing Calf Raise", "50", ""),
      ...xN(4, "Outer Thigh (Abductor)", "80", "10"),
    ],
  },
  {
    date: "2026-07-27",
    title: "Legs",
    notes:
      "Used the easier seated leg press machine. Inner thigh: third set was hard by rep 9. Outer thigh: on the last two sets did not do my best after reps 9 and 10.",
    sets: [
      s("Leg Extension", "95", "12"),
      s("Leg Extension", "100", "12"),
      s("Leg Extension", "110", "12"),
      s("Seated Leg Press (Easier Machine)", "160", "10"),
      s("Seated Leg Press (Easier Machine)", "180", "10"),
      ...xN(2, "Seated Leg Press (Easier Machine)", "180", "12"),
      s("Prone Leg Curl", "55", "13"),
      s("Prone Leg Curl", "55", "12"),
      s("Prone Leg Curl", "50", "12"),
      ...xN(3, "Inner Thigh (Adductor)", "100", "11"),
      s("Outer Thigh (Abductor)", "80", "12"),
      s("Outer Thigh (Abductor)", "90", "10"),
      ...xN(2, "Outer Thigh (Abductor)", "80", "12"),
      ...xN(2, "Standing Calf Raise", "60", "15"),
      s("Standing Calf Raise", "60", "12"),
    ],
  },
  {
    date: "2026-07-28",
    title: "Pull — back and biceps",
    notes:
      "Right shoulder clicking on low rows. High rows: trying to find the right weight. Lat pulldowns: something in the forearm popping. Biceps were not easy — the earlier exercises used up the energy. Cross body hammer curls are one of my biggest weaknesses: sloppy.",
    sets: [
      ...xN(2, "Low Row", "50", "12"),
      s("Low Row", "60", "10"),
      s("Low Row", "50", "10"),
      s("High Row", "70", "6"),
      s("High Row", "60", "6"),
      s("High Row", "50", "8"),
      s("High Row", "50", "12"),
      s("Lat Pulldown", "60", "10"),
      s("Lat Pulldown", "60", "11"),
      ...xN(2, "Dumbbell Bicep Curl", "20", "5"),
      ...xN(3, "Hammer Curl (Cross Body)", "15", "7"),
    ],
  },
  {
    date: "2026-07-30",
    title: "Legs and triceps",
    notes:
      "Used the easier leg press machine. Outer thigh 90 lbs: the 13th rep was not the best but not bad either. Inner thigh: hit that 9th rep limit on set 3 again, tapered to 90 for 2 then 80 for 3. Tricep pushdown last set got really hard after rep 9.",
    sets: [
      s("Leg Press (Easier Machine)", "160", "12"),
      s("Leg Press (Easier Machine)", "180", "12"),
      ...xN(2, "Leg Press (Easier Machine)", "180", "15"),
      ...xN(4, "Prone Leg Curl", "55", "12"),
      ...xN(2, "Outer Thigh (Abductor)", "80", "13"),
      s("Outer Thigh (Abductor)", "90", "13"),
      s("Outer Thigh (Abductor)", "80", "13"),
      s("Inner Thigh (Adductor)", "100", "11"),
      s("Inner Thigh (Adductor)", "100", "13"),
      s("Inner Thigh (Adductor)", "100", "9"),
      s("Inner Thigh (Adductor)", "90", "2"),
      s("Inner Thigh (Adductor)", "80", "3"),
      s("Tricep Pushdown", "20", "17"),
      ...xN(2, "Tricep Pushdown", "20", "15"),
      s("Tricep Pushdown", "20", "12"),
      ...xN(4, "Standing Calf Raise", "70", "15"),
      s("Leg Extension", "100", "13"),
      s("Leg Extension", "110", "13"),
      s("Leg Extension", "110", "15"),
    ],
  },
  {
    date: "2026-08-03",
    title: "Legs",
    notes:
      "Prone leg curls: had to switch down to 55 lbs on the last set due to fatigue. Easier leg press last set: 10 reps, 15 second break, then 5 more. Inner thigh: feel like I am not improving on these — help. Outer thigh: dropped 90 to 80 to 70 to 60 until failure, about 3-5 reps each; feel like I am not improving, need better structure or maybe daily stretches too.",
    sets: [
      s("Prone Leg Curl", "55", "13"),
      ...xN(2, "Prone Leg Curl", "60", "12"),
      s("Prone Leg Curl", "60", "7"),
      s("Prone Leg Curl", "55", "5"),
      ...xN(3, "Leg Press (Easier Machine)", "180", "15"),
      s("Leg Press (Easier Machine)", "180", "15"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "10"),
      s("Inner Thigh (Adductor)", "110", "7"),
      s("Inner Thigh (Adductor)", "100", "4"),
      s("Inner Thigh (Adductor)", "100", "9"),
      ...xN(2, "Outer Thigh (Abductor)", "80", "15"),
      s("Outer Thigh (Abductor)", "70", "12"),
      s("Outer Thigh (Abductor)", "90", "4"),
      s("Outer Thigh (Abductor)", "80", "4"),
      s("Outer Thigh (Abductor)", "70", "4"),
      s("Outer Thigh (Abductor)", "60", "4"),
      s("Standing Calf Raise", "60", "15"),
      s("Standing Calf Raise", "80", "12"),
      s("Standing Calf Raise", "80", "13"),
      s("Standing Calf Raise", "80", "11"),
    ],
  },
  {
    date: "2026-08-04",
    title: "Pull — back and biceps",
    notes:
      "Mid rows: do not feel anything in the mid back, might be overthinking it or doing them wrong. Lat pulldowns: last two sets the shoulders kept clicking, almost like it restricts the full movement, but it was fine at the start. Bicep curls: struggling a lot, stuck on 15-20 lbs for several months. Cross body hammer curls at 17.5 were pretty hard — is this even the right exercise for the brachialis?",
    sets: [
      ...xN(3, "Low Row", "50", "15"),
      s("Low Row", "60", "12"),
      ...xN(2, "Seated Mid Row", "50", "15"),
      s("Seated Mid Row", "40", "5"),
      s("Seated Mid Row", "50", "4"),
      ...xN(2, "Lat Pulldown", "60", "13"),
      s("Lat Pulldown", "60", "10"),
      s("Lat Pulldown", "60", "6"),
      s("Lat Pulldown", "50", "3"),
      ...xN(2, "Dumbbell Bicep Curl", "20", "8"),
      ...xN(2, "Dumbbell Bicep Curl", "17.5", "8"),
      s("Hammer Curl (Cross Body)", "17.5", "4"),
      s("Hammer Curl (Cross Body)", "15", "10"),
    ],
  },
  {
    date: "2026-08-06",
    title: "Legs",
    notes:
      "Used the easier leg press machine. Outer thigh done leaning forward — took a few sets to find the weight.",
    sets: [
      ...xN(3, "Leg Press (Easier Machine)", "180", "15"),
      s("Leg Press (Easier Machine)", "200", "15"),
      ...xN(3, "Prone Leg Curl", "55", "13"),
      s("Prone Leg Curl", "50", "12"),
      s("Outer Thigh (Abductor, Leaning Forward)", "60", "8"),
      s("Outer Thigh (Abductor, Leaning Forward)", "50", "10"),
      s("Outer Thigh (Abductor, Leaning Forward)", "60", "5"),
      ...xN(2, "Outer Thigh (Abductor, Leaning Forward)", "60", "12"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "12"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "13"),
      s("Standing Calf Raise", "80", "13"),
      s("Standing Calf Raise", "80", "7"),
      s("Standing Calf Raise", "70", "8"),
      ...xN(4, "Leg Extension", "110", "13"),
    ],
  },
  {
    date: "2026-08-07",
    title: "Pull and triceps",
    notes: "",
    sets: [
      s("Tricep Pushdown", "20", "15"),
      ...xN(2, "Tricep Pushdown", "30", "9"),
      s("Tricep Pushdown", "20", "12"),
      s("Low Row", "50", "15"),
      s("Low Row", "60", "8"),
      s("Low Row", "60", "6"),
      s("Low Row", "50", "12"),
      ...xN(3, "Seated Mid Row", "40", "15"),
      s("Seated Mid Row", "40", "11"),
      ...xN(3, "Lat Pulldown", "60", "12"),
      s("Lat Pulldown", "60", "10"),
    ],
  },
  {
    date: "2026-08-11",
    title: "Legs and arms",
    notes:
      "Prone leg curls: second set got harder around rep 9-10; third set the last few were hard and the last two were debatable as full reps — I do somewhat deep pulls. Standing calves: wore flat Vans instead of the Asics Superblast 2s which might have cut my 80 lb reps; the last 3 reps of the 70 lb set felt limited in range of motion. Calves feel tight like a good workout but weight and reps are unclear.",
    sets: [
      ...xN(3, "Dumbbell RDL", "20", "12"),
      ...xN(3, "Horizontal Leg Press", "200", "12"),
      s("Prone Leg Curl", "55", "13"),
      s("Prone Leg Curl", "55", "13"),
      s("Prone Leg Curl", "55", "13"),
      ...xN(2, "Inner Thigh (Adductor)", "100", "15"),
      ...xN(3, "Leg Extension", "110", "15"),
      s("Outer Thigh (Abductor)", "80", "10"),
      s("Outer Thigh (Abductor)", "70", "5"),
      s("Outer Thigh (Abductor)", "80", "6"),
      s("Standing Calf Raise", "80", "13"),
      s("Standing Calf Raise", "80", "8"),
      s("Standing Calf Raise", "70", "13"),
      ...xN(3, "Dumbbell Bicep Curl", "15", "12"),
      ...xN(3, "Hammer Curl (Cross Body)", "15", "12"),
    ],
  },
  {
    date: "2026-08-11",
    title: "Pull and triceps",
    notes: "Finished with 30 inclined ab crunches.",
    sets: [
      s("Tricep Pushdown", "30", "9"),
      ...xN(2, "Tricep Pushdown", "30", "11"),
      ...xN(2, "Overhead Dumbbell Tricep Extension", "10", "12"),
      s("Lat Pulldown", "70", "11"),
      ...xN(2, "Lat Pulldown", "70", "10"),
      ...xN(3, "Seated Mid Row", "40", "15"),
      s("Low Row", "60", "9"),
      s("Low Row", "60", "5"),
      s("Low Row", "60", "6"),
      s("Low Row", "50", "4"),
      s("Low Row", "50", "9"),
      s("Inclined Ab Crunch", "", "30"),
    ],
  },
  {
    date: "2025-08-14",
    title: "Legs and arms",
    notes:
      "Prone leg curls: first set was 12 reps at 55 then 3 at 60 as one set. Leg extension: short 3 second pause after the 10th rep on the last set.",
    sets: [
      s("Horizontal Leg Press", "200", "15"),
      ...xN(2, "Horizontal Leg Press", "220", "15"),
      s("Prone Leg Curl", "55", "12"),
      s("Prone Leg Curl", "60", "3"),
      ...xN(2, "Prone Leg Curl", "60", "12"),
      ...xN(2, "Inner Thigh (Adductor)", "110", "15"),
      ...xN(3, "Outer Thigh (Abductor)", "70", "12"),
      ...xN(2, "Leg Extension", "110", "15"),
      s("Leg Extension", "110", "13"),
      ...xN(2, "Standing Calf Raise", "80", "10"),
      s("Standing Calf Raise", "80", "11"),
      ...xN(3, "Dumbbell Bicep Curl", "20", "8"),
      s("Hammer Curl (Cross Body)", "17.5", "8"),
      ...xN(2, "Hammer Curl (Cross Body)", "17.5", "9"),
    ],
  },
  {
    date: "2026-08-17",
    title: "Legs and arms",
    notes:
      "Cross body hammer curls: last set 12 reps on the right but only 10 on the left because the left wrist was acting up.",
    sets: [
      ...xN(3, "Horizontal Leg Press", "220", "15"),
      ...xN(2, "Prone Leg Curl", "60", "10"),
      s("Prone Leg Curl", "60", "13"),
      ...xN(2, "Leg Extension", "110", "15"),
      s("Leg Extension", "110", "14"),
      ...xN(2, "Inner Thigh (Adductor)", "110", "15"),
      ...xN(3, "Outer Thigh (Abductor)", "70", "13"),
      ...xN(2, "Standing Calf Raise", "80", "12"),
      s("Standing Calf Raise", "80", "8"),
      s("Dumbbell Bicep Curl", "20", "9"),
      s("Dumbbell Bicep Curl", "20", "8"),
      s("Dumbbell Bicep Curl", "20", "9"),
      ...xN(2, "Hammer Curl (Cross Body)", "17.5", "12"),
      s("Hammer Curl (Cross Body)", "17.5", "11"),
    ],
  },
  {
    date: "2026-08-18",
    title: "Pull, triceps and abs",
    notes:
      "Lat pulldowns: 70 lbs was easy, 85 lbs was good overall — thinking more reps at 70 with some exposure to 85.",
    sets: [
      ...xN(3, "Tricep Pushdown", "30", "12"),
      ...xN(2, "Overhead Dumbbell Tricep Extension", "10", "14"),
      s("Overhead Dumbbell Tricep Extension", "10", "13"),
      s("Overhead Dumbbell Tricep Extension", "10", "12"),
      ...xN(2, "Lat Pulldown", "70", "12"),
      s("Lat Pulldown", "85", "9"),
      ...xN(2, "Low Row", "50", "15"),
      s("Low Row", "50", "14"),
      ...xN(3, "Seated Mid Row", "40", "15"),
      s("Ab Crunch", "40", "20"),
      s("Ab Crunch", "40", "10"),
      s("Ab Crunch", "40", "5"),
      s("Ab Crunch", "40", "7"),
    ],
  },
  {
    date: "2026-08-20",
    title: "Legs, arms and abs",
    notes:
      "Dumbbell bicep curls done with mismatched weights (22.5 / 20) and swapped arms between sets. Cross body curls: worth watching more videos on proper technique.",
    sets: [
      ...xN(3, "Horizontal Leg Press", "240", "12"),
      ...xN(2, "Prone Leg Curl", "60", "12"),
      s("Prone Leg Curl", "60", "13"),
      s("Inner Thigh (Adductor)", "120", "11"),
      s("Inner Thigh (Adductor)", "120", "13"),
      ...xN(3, "Leg Extension", "120", "14"),
      ...xN(3, "Outer Thigh (Abductor)", "70", "14"),
      ...xN(2, "Standing Calf Raise", "80", "12"),
      s("Standing Calf Raise", "80", "9"),
      ...xN(3, "Dumbbell Bicep Curl", "21.25", "9"),
      ...xN(3, "Hammer Curl (Cross Body)", "17.5", "12"),
      s("Inclined Ab Crunch", "40", "15"),
      s("Inclined Ab Crunch", "40", "12"),
      s("Inclined Ab Crunch", "40", "11"),
    ],
  },
  {
    date: "2026-08-21",
    title: "Pull and triceps",
    notes: "",
    sets: [
      s("Tricep Pushdown", "40", "8"),
      ...xN(2, "Tricep Pushdown", "30", "14"),
      ...xN(2, "Overhead Dumbbell Tricep Extension", "10", "14"),
      ...xN(2, "Overhead Dumbbell Tricep Extension", "10", "14"),
      ...xN(2, "Lat Pulldown", "70", "14"),
      s("Lat Pulldown", "85", "10"),
      ...xN(2, "Low Row", "50", "15"),
      s("Low Row", "50", "13"),
      ...xN(3, "Face Pull", "30", "10"),
    ],
  },
  {
    date: "2026-08-24",
    title: "Legs and arms",
    notes:
      "Prone leg curls: last 3 reps of the third set could have been better. Cross body curls: lost count on the second set, did it to failure, probably about 10 reps.",
    sets: [
      ...xN(3, "Horizontal Leg Press", "240", "13"),
      s("Prone Leg Curl", "60", "13"),
      s("Prone Leg Curl", "60", "14"),
      s("Prone Leg Curl", "60", "13"),
      ...xN(2, "Leg Extension", "120", "15"),
      s("Leg Extension", "120", "13"),
      ...xN(2, "Dumbbell Bicep Curl", "25", "8"),
      s("Dumbbell Bicep Curl", "25", "4"),
      s("Hammer Curl (Cross Body)", "17.5", "15"),
      s("Hammer Curl (Cross Body)", "17.5", "10"),
    ],
  },
  {
    date: "2026-08-28",
    title: "Legs",
    notes:
      "Prone leg curls: last 3 reps of the final set could have been better — at this point the prone leg curl progression feels like it is going to be stagnant.",
    sets: [
      ...xN(3, "Prone Leg Curl", "60", "14"),
      ...xN(3, "Leg Extension", "120", "15"),
      ...xN(3, "Horizontal Leg Press", "240", "13"),
      ...xN(2, "Outer Thigh (Abductor)", "70", "13"),
    ],
  },
  {
    date: "2026-08-31",
    title: "Legs and arms",
    notes: "Standing calves opened with a 70 lb warmup set.",
    sets: [
      ...xN(3, "Horizontal Leg Press", "240", "14"),
      ...xN(2, "Prone Leg Curl", "60", "14"),
      s("Prone Leg Curl", "65", "10"),
      ...xN(3, "Outer Thigh (Abductor)", "70", "13"),
      s("Leg Extension", "120", "15"),
      s("Leg Extension", "130", "15"),
      s("Leg Extension", "130", "11"),
      ...xN(2, "Inner Thigh (Adductor)", "120", "15"),
      s("Standing Calf Raise", "70", "12"),
      s("Standing Calf Raise", "80", "12"),
      s("Standing Calf Raise", "80", "10"),
      ...xN(3, "Dumbbell Bicep Curl", "20", "10"),
      ...xN(3, "Hammer Curl (Cross Body)", "20", "8"),
    ],
  },
  {
    date: "2026-09-02",
    title: "Pull and triceps",
    notes: "",
    sets: [
      s("Tricep Pushdown", "40", "10"),
      s("Tricep Pushdown", "30", "15"),
      s("Tricep Pushdown", "40", "4"),
      s("Tricep Pushdown", "30", "7"),
      s("Tricep Pushdown", "30", "13"),
      ...xN(3, "Overhead Dumbbell Tricep Extension", "10", "15"),
      ...xN(2, "Lat Pulldown (Wide Grip)", "70", "15"),
      s("Lat Pulldown (Wide Grip)", "85", "10"),
      ...xN(3, "Low Row (Close Grip)", "50", "15"),
    ],
  },
  {
    date: "2026-09-03",
    title: "Legs and arms",
    notes: "Hack squats opened at 25 lbs per side then moved to 35 per side.",
    sets: [
      s("Hack Squat", "50", "8"),
      ...xN(2, "Hack Squat", "70", "10"),
      s("Prone Leg Curl", "65", "10"),
      s("Prone Leg Curl", "65", "9"),
      s("Prone Leg Curl", "65", "10"),
      s("Leg Extension", "130", "15"),
      ...xN(2, "Leg Extension", "130", "10"),
      s("Outer Thigh (Abductor)", "70", "14"),
      s("Outer Thigh (Abductor)", "80", "9"),
      s("Outer Thigh (Abductor)", "70", "5"),
      s("Outer Thigh (Abductor)", "70", "14"),
      s("Outer Thigh (Abductor)", "60", "11"),
      ...xN(2, "Inner Thigh (Adductor)", "120", "15"),
      s("Standing Calf Raise", "80", "13"),
      s("Standing Calf Raise", "80", "11"),
      s("Standing Calf Raise", "80", "10"),
      ...xN(2, "Dumbbell Bicep Curl", "20", "10"),
      s("Dumbbell Bicep Curl", "25", "7"),
      ...xN(2, "Hammer Curl (Cross Body)", "20", "10"),
      s("Hammer Curl (Cross Body)", "20", "8"),
    ],
  },
];

/** Total sets across the whole backlog — shown on the import screen. */
export const BACKLOG_SET_COUNT = BACKLOG.reduce((n, w) => n + w.sets.length, 0);
